apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: autosync-guestbook
  namespace: argocd
spec: 
  destination: 
    namespace: autosync-guestbook
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: autosync-guestbook
    repoURL: "https://github.com/dbarattini-pg/argocd-lab-apps"
    targetRevision: main
    directory:
      recurse: true
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
